export interface Element {
    type: htmlInput,
    name: string,
    id: string,
    value: string,
    size: string,
    maxlength: string,
    min: string,
    max: string,
    pattern: string,
    required: boolean,
    step: string,
    width: string,
    height: string,
    list: string,
    label: string,
    placeholder: string,
    options: [string],
    isMulti: boolean,
}

export enum htmlInput {
    TEXT = 'text', 
    NUMBER = 'number', 
    SELECT = 'select',
    RADIO = 'radio',
    DATE = 'date',
    PASSWORD = 'password',
    CHECKBOX = 'checkbox',
    EMAIL = 'email', 
    HIDDEN = 'hidden', 
    IMAGE = 'image',
    MONTH = 'month', 
    DATETIME = 'datetime-local',
    RANGE = 'range',
    RESET = 'reset',
    SEARCH = 'search',
    SUBMIT = 'submit',
    TEL = 'tel',
    TIME ='time',
    URL = 'url',
    WEEK = 'week',
    TEXTAREA = 'textarea', 
    DATALIST ='datalist'
}
